CREATE TABLE paper (
ID INT PRIMARY KEY AUTO_INCREMENT,
HEIGHT DOUBLE(3,3),
WIDTH DOUBLE(3,3),
GSM INT,
Textweight INT,
Coverweight INT,
Bond INT,
Sheets INT,
Brand VARCHAR(50),
Price DOUBLE(5,2),
Price_Per_Page DOUBLE(5,2),
Material VARCHAR(50),
Color VARCHAR(50),
Printer_Compatability VARCHAR(50),
Feature VARCHAR(50),
Additional_Description VARCHAR(5000),
link_to_vendor VARCHAR(500));